# Generated by Django 4.0 on 2022-01-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('Date', models.DateField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('Date', models.DateField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('Marque', models.CharField(max_length=40)),
                ('couleur', models.CharField(max_length=60)),
                ('prix', models.FloatField(max_length=40)),
                ('modele', models.CharField(max_length=40)),
                ('numerosachet', models.CharField(max_length=40)),
                ('id_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.image')),
                ('id_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.operation')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
        migrations.AddField(
            model_name='user',
            name='id_voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.voiture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.user'),
        ),
        migrations.AddField(
            model_name='facture',
            name='id_voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.voiture'),
        ),
    ]
