# Generated by Django 4.0.1 on 2022-01-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_facture_image_operation_user_voiture_delete_todo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.ImageField(null=True, upload_to='todo/static/image'),
        ),
    ]
