# Generated by Django 4.0.1 on 2022-01-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(null=True, upload_to='Bourse/static/image')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('Date', models.DateField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('Marque', models.CharField(max_length=40)),
                ('couleur', models.CharField(max_length=60)),
                ('prix', models.FloatField(max_length=40)),
                ('modele', models.CharField(max_length=40)),
                ('numerosachet', models.CharField(max_length=40)),
                ('id_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bourse.image')),
                ('id_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bourse.operation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel', models.IntegerField()),
                ('id_voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bourse.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('Date', models.DateField(max_length=50)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bourse.user')),
                ('id_voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bourse.voiture')),
            ],
        ),
    ]
