# Generated by Django 4.0.1 on 2022-01-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=60)),
                ('prix', models.FloatField(max_length=40)),
                ('modele', models.CharField(max_length=40)),
                ('numerosachet', models.CharField(max_length=40)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='Bourse.client')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='Bourse.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(null=True, upload_to='static/image')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Bourse.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ACHAT', 'Achat'), ('VENDRE', 'Vendre')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Bourse.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Bourse.voiture')),
            ],
        ),
    ]
