# Generated by Django 4.0.1 on 2022-01-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='facture',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='id_image',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='id_operation',
        ),
        migrations.AddField(
            model_name='image',
            name='id_voiture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bourse.voiture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='id_voiture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bourse.voiture'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='facture',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bourse.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voiture',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bourse.client'),
            preserve_default=False,
        ),
    ]
