# Generated by Django 4.0.1 on 2022-01-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bourse', '0002_voiture_image_alter_facture_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='client',
        ),
    ]
