# Generated by Django 4.0.1 on 2022-02-04 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bourse', '0003_remove_voiture_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='Bourse.client'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='Bourse.voiture'),
        ),
    ]
