# Generated by Django 4.0.1 on 2022-02-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bourse', '0006_alter_operation_voiture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='voiture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bourse.voiture'),
        ),
    ]
